POST http://localhost:3000/auth
content-type: application/json
Authorization: Bearer setYourSuperSecretMasterTokenHere

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer setYourSuperSecretMasterTokenHere

{
    "username": "ucup",
    "password": "thisisobviouslynotmypassword"
}

###

POST http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer setYourSuperSecretMasterTokenHere

{
    "username": "udin",
    "password": "thisisobviouslynotmypassword"
}

###
POST http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer setYourSuperSecretMasterTokenHere

{
    "username": "usnu",
    "password": "thisisobviouslynotmypassword"
}

